contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
]

widget_tweaks_article/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls'))
]

contact/models.py
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(max_length=200, blank=False, null=True)
    last_name = models.CharField(max_length=200, blank=False, null=True)
    email = models.EmailField(max_length=300, blank=False, null=True)
    phone = models.CharField(max_length=100, blank=True, null=True)
    subject = models.CharField(max_length=200, blank=False, null=False)
    message = models.TextField()

    def __str__(self):
        return self.subject

contact/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

contact/views.py
from django.shortcuts import render
from .forms import ContactForm


def contact(request):
    form = ContactForm()

    context = {'form': form}
    return render(request, 'contact/contact.html', context)

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<section class="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 text-center my-5 p-4 form-container">
                <h1>Contact Us</h1>
                <form method="POST">
                    {% csrf_token %}
                    <!-- If any hidden fields -->
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    <!-- end -->

                    <div class="form-floating mb-2">
                        {% render_field form.first_name class="form-control" placeholder=form.text.label%}
                        <label for="id_first_name">First Name:*</label>
                        <!-- Rendering field errors -->
                        {% for error in form.first_name.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <div class="form-floating mb-2">
                        {% render_field form.last_name class="form-control" placeholder=form.text.label%}
                        <label for="id_last_name">Last Name:*</label>
                        <!-- Rendering field errors -->
                        {% for error in form.last_name.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <div class="form-floating mb-2">
                        {% render_field form.email class="form-control" placeholder=form.text.label%}
                        <label for="id_email">Email:*</label>
                        <!-- Rendering field errors -->
                        {% for error in form.email.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <div class="form-floating mb-2">
                        {% render_field form.phone class="form-control" placeholder=form.text.label%}
                        <label for="id_phone">Phone:</label>
                        <!-- Rendering field errors -->
                        {% for error in form.phone.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <div class="form-floating mb-2">
                        {% render_field form.subject class="form-control" placeholder=form.text.label%}
                        <label for="id_subject">Subject:*</label>
                        <!-- Rendering field errors -->
                        {% for error in form.subject.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <div class="form-group mb-4">
                        <label for="id_message" class="form-label">Message:</label>
                        {% render_field form.message|attr:"maxlength:2500" class="form-control" rows="5"%}
                        {% for error in form.message.errors %}
                        <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    </div>

                    <!-- Rendering Generic Form Errors -->
                    {% if form.non_field_errors %}
                    <div>
                        <span class="text-danger"> {{ form.non_field_errors }}</span>
                    </div>
                    {% endif %}

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Send</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <title>Contact</title>
</head>

<body>


    {% block content %}
    {% endblock content%}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>